name: mobileapp_scabies
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  google_fonts: ^6.1.0
  provider: ^6.1.1
  iconly: ^1.0.1
  percent_indicator: ^4.2.3
  camera: ^0.10.5+7
  path_provider: ^2.1.1
  path: ^1.8.3
  get_it: ^7.6.4
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  # carousel_slider: ^4.2.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
